AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Template do deploy a simple website

Resources:

  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
    DeletionPolicy: Delete

Outputs:

  S3Bucket:
    Value: !Ref S3Bucket
    Description: Website S3 Bucket

  WebSiteUrl:
    Value: !Join
    - ''
    - - 'https://'
      - !GetAtt
        - S3Bucket
        - DomainName
      - '/index.html'
    Description: URL to use to access the website

  ParentOriginForLexWebUi:
    Value: !Join
      - ''
      - - 'https://'
        - !GetAtt
          - S3Bucket
          - DomainName
    Description: Parent origin to specify for lex-web-ui